name: test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
          check-latest: true
          cache-dependency-path: subdir/go.sum
      - name: Run tests for mock
        run: go test ./...
  